### PR TITLE
Fix for L5.1 codebase

### PR DESCRIPTION
**Pull request by mattglover11**
Minor fix for passing the 'potion' only section of config to the commands instead of the entire config block
Moderate fixed to the service provider to handle the deprecated call to createMatcher (which returns a regex version of the supplied pattern)

### CODE REVIEW

**Comment by mattrmiller** [comment]
Thank you for your contribution. I will try to find some time this week to go over both of your pull requests and test them out, and make sure they are in line with the intention of the project.

**Comment by mattglover11** [comment]
You're welcome.

In my fork, I'll be adding two major features next week.
1. Ability to safe the cached assets to a config file rather than a transient cache file. This will aid multi-site deployments (and prevents the need to include a variable cache path in deployment plans)
2. Asset queuing. The ability to insert a trigger in a blade template to invoke the compilation of a specific potion. This would enable page specific potion inclusions to be kept up to date. It would also allow your common set of options to be maintained via your central layouts. Avoids the need and cumbersome nature of watchers.

Cheers Matt

**Comment by mattrmiller** [comment]
If I am understanding #1 correctly. The current path will support this. Most multi site deployments will have balanced caching with redis, memcache, etc. Which will most always be faster that a config file.

**Comment by mattrmiller** [comment]
#2, the current setup supports specific page assets, with groups, which means assets will be compiled not in line with the request, which could slow the request down. Granted only for the first run, but this package views asset compilation as a server function and not a HTTP request function.

**Comment by mattglover11** [comment]
Re #1 - the cache file gets rendered to /storage/framework/cache/{random}/{random}/{unique} which does work across multiple environments, it's just clumsy to have to go into the cache, indentify the correct transitory file and upload it to the next environment (in my use case, local to dev, dev to staging, staging to preproduction, preproduction to production). In this case I'm more concerned initially about deployment automation and repeatability. I'm suggesting writing out the cache (OPTIONALLY) to a config such as config_path(potion.assets.php) which could be used in a subsequent iteration to seed redis or memcache.

I am certainly not going to be running "php artisan potion:make-assets" in a production environment so I need to be able to transport the cache there. I thinking the config file is step one and achieves the objective of cache portability without being any more i/o intensive than the cache itself. Step two is probably a provider to seed/refresh memcache/redis if required on large scale systems.

**Comment by mattglover11** [comment]
Re #2 - I'm in agreement that HTTP response is **king** here. I find file "watcher" mechanisms to be cumbersome and a hit on productivity. I understand that the potion config already supports grouping and individual files - I'm looking at productivity here as the main use case with zero impact to HTTP response being a mandatory requirement. So, my thinking is, rather than have something like:

```
php artisan potion:make-asset {specific-potion}
```

... to compile a specific potion (though i think that makes sense), I'm suggesting that in practice, it is still a PIA to move from the development environment to a shell to quaff the magic potion you are working on. :D

I'm mulling over a blade helper that could trigger the above (though not via a console command) for a specific page which may or may not include a dependency.... for example:

```
{{ Potion::queue('potion_name', 'dependency') }}
```

ie.

```
{{ Potion::queue('home_page', 'main_styles') }}
```

I'm thinking (out loud) that the blade helper would be activated or deactivated globally such that outside of dev, the queue does nothing. But inside my dev environment, queing will (probably):
- synchronously checksum and compare the inputs; 
- determine the need to recompile;
- compile if required and output the assets; 
- update the cache; and, 
- rewrite the config from #1 above.

In doing so, I can be editing my SCSS files or JS, and refresh my browser on the specific page without needing to go to a shell, or wait for an offline "watcher" to recompile EVERYTHING rather than just what I need.

Thoughts?

**Comment by mattrmiller** [comment]
#1 Kind of doesn't follow best practices with deployments and the "storage" directory, nor using file caching for balanced web server architecture.

#2 Interacting with the queue via blade sounds like a very big work around for something that can be handled very easily via asset groups. It kind of also breaks the framework mind set with MVC and Services that Laravel has done so well in getting developers used to.

I appreciate your contributions and ideas, and obviously the blessing of open source is you have your branch for what works for you and your systems. However neither of those features will be something I feel is good to bring into the main branch at this time, however if/when you have it completed I will take a look at reconsider.

I have put aside some time tonight to take a look at getting the main branch 5.1 compatible with your contributions. It's been slow as I have spent a lot of time with clients just getting them to L4, so hopefully over next months I will be back in the L5 world and able to move forward from there.

Thanks again.

**Comment by mattglover11** [comment]
No problems - I won't proactively push PR's at this point and will await your contact regarding bring anything in from my fork.

**Comment by mattrmiller** [comment]
I did a manual merge of some of your contributions. Thanks again. Look forward to seeing what you continue in your branch.

**Pull request closed without merging**
